language: python
# python versions
python:
    - "3.6.9"
env:
    -DATABASE_URL=postgresql+psycopg2://postgres@localhost/mytestingdb
    -SECRET_KEY=mysecretkey
    -APP_ENV=testing
services:
    - "postgresql"
# install requirements
install:
    - pip install -r requirements.txt
    - pip install python-coveralls
    - psql -c 'CREATE DATABASE mytestingdb;' -U postgres
# To run tests
script:
    - coverage run manage.py test
# send coverage report to coveralls
after_success:
    coveralls