language: python
# python versions
python:
    - "3.6.9"
env:
    -SECRET_KEY=mysecretkey
    -APP_ENV=testing
# install requirements
install:
    - pip install -r requirements.txt
    - pip install python-coveralls
# To run tests
script:
    - coverage run manage.py test
# send coverage report to coveralls
after_success:
    coveralls