version: '3.3'

services:
  api:
    command: >
      sh -c "python manage.py load_initial_data  &&
        uwsgi --thunder-lock --ini uwsgi.ini"
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: mysecretkey
      APP_ENV: dev
